In [17]:
# Import required libraries
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

In [18]:
# Load the Iris dataset
iris = load_iris()

In [19]:
# Convert data and target into a data frame
# Extract the First 100 Features
X = pd.DataFrame(data=iris.data[:100+(13%50), :], columns=iris.feature_names)
y = pd.DataFrame(data=iris.target[:100+(13%50)], columns=['irisType'])

In [20]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
# Convert targets to categorical (one-hot encoding)
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

In [23]:
# Define the Perceptron model using a single dense layer
model = tf.keras.Sequential([
    tf.keras.layers.Dense(3, activation='softmax', input_shape=(X_train.shape[1],))
])

/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [24]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [25]:
# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=1, verbose=1)

Epoch 1/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 182us/step - accuracy: 0.5671 - loss: 1.0114     
Epoch 2/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 141us/step - accuracy: 0.5786 - loss: 0.9196
Epoch 3/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 141us/step - accuracy: 0.5372 - loss: 0.8485  
Epoch 4/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 143us/step - accuracy: 0.6710 - loss: 0.6779
Epoch 5/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 160us/step - accuracy: 0.7106 - loss: 0.6358  
Epoch 6/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 155us/step - accuracy: 0.6861 - loss: 0.6495
Epoch 7/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 153us/step - accuracy: 0.7903 - loss: 0.4892  
Epoch 8/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 154us/step - accuracy: 0.8605 - loss: 0.4478
Epoch 9/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 153us/step - accuracy: 0.7604 - loss: 0.5155
Epoch 10/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 158us/step - accuracy: 0.8425 - loss: 0.5031
Epoch 11/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - accuracy: 0.8531 - loss: 0.4301
Epoch 12/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s

In [26]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=1)
y_test_classes = y_test.argmax(axis=1)

# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test_classes, y_pred_classes)
print("Accuracy:", accuracy)

# Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n", confusion_matrix(y_test_classes, y_pred_classes))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Accuracy: 0.9130434782608695
Perceptron Confusion Matrix:
 [[11  0  0]
 [ 0 10  0]
 [ 0  2  0]]
